language: node_js
dist: trusty
sudo: false
node_js:
- "8"
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run test
- ls -a
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
