// flow-typed signature: b16eaa2379ed419de1e4bb5cd19bf4af
// flow-typed version: <<STUB>>/feeles-ide_v^0.3.18/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feeles-ide'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feeles-ide' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feeles-ide/feeles-webpack-plugin' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/CardContainer' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/CardWindow' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/CreditsCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/CustomizeCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/defaultState' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditFile' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/AssetButton' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/AssetPane' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/codemirror-hint-extension' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/CreditBar' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/Editor' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/ErrorPane' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/PlayMenu' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/Preview' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/SourceEditor' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EditorCard/zenkakuToHankaku' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EnvCard/EnvItem' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/EnvCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/DesktopFile' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/DirCard' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/FileCard' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/Filename' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/getHierarchy' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/Root' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/search' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/SearchBar' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/HierarchyCard/TrashBox' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MediaCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/ErrorMessage' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/Monitor' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/registerHTML' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/ResolveProgress' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/Screen' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/setSrcDoc' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/MonitorCard/SvgButton' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/PaletteCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/PaletteCard/LayeredStyle' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ReadmeCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ReadmeCard/Readme' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ScreenShotCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ShotCard/codemirror-hint-extension' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ShotCard/Editor' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ShotCard/excessiveCare' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ShotCard/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Cards/ShotCard/ShotPane' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/ChromeTab/ChromeTab' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/ChromeTab/ChromeTabContent' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/ChromeTab/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/ChromeTab/Tab' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/database/FileView' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/database/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/database/personalDB' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/_File' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/babelFile' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/BinaryFile' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/composeEnv' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/configs' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/JSON6' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/makeFromElement' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/makeFromFile' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/sanitizeHTML' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/separate' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/Snippet' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/SourceFile' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/File/validateType' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/AddDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/Buttons' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/DeleteDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/FileDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/FilenameInput' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/PreferenceDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/SaveDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/FileDialog/SignDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/js/codemirrorStyle' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/js/getCustomTheme' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/js/isServiceWorkerEnabled' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/EditableLabel' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/Footer' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/init' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/LaunchDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/Main' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/MDReactComponent' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/ReactPopout' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/jsx/RootComponent' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/lib/connector' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/lib/escape-loader' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/lib/require' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/lib/screen' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/localization/en' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/localization/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/localization/ja' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Menu/AboutDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Menu/CloneDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Menu/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Menu/Menu' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/Menu/MetaDialog' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/organization' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/CodeMirrorComponent' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/debugWindow' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/dragTypes' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/FacebookIcon' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/GoogleIcon' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/MonitorTypes' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/open' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/resolveOrigin' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/Rollbar' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/TwitterIcon' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/uniqueBy' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/utils/uniqueId' {
  declare module.exports: any;
}

declare module 'feeles-ide/lib/workers/babel.worker' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/ask/ask' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/ask/icon' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/ask/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/ask/internet' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/ask/lib/interrupt' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/ask/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/feeles/eval' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/i18n/en_US/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/i18n/en_US/preload' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/i18n/ja_JP/code' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/i18n/ja_JP/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/i18n/ja_JP/preload' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/lib/interrupt' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/hello-world/sub/message' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/airFriction/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/airFriction/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/airFriction/settings' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/airFriction/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/angle/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/angle/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/angle/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/attractors/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/avalanche/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/ballPool/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/bridge/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/bridge/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/bridge/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/broadphase/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/car/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/car/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/car/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/catapult/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/catapult/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/catapult/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/chains/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/chains/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/chamfer/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/chamfer/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/chamfer/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/circleStack/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/circleStack/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/circleStack/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/cloth/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/coins/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/coins/sensor' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/coins/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/coins/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/collisionFiltering/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/compositeManipulation/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/compound/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/compound/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/compound/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/compoundStack/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/compoundStack/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/compoundStack/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/concave/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/constraint/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/constraint/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/constraint/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/density/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/density/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/density/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/engine' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/engineConfigs' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/events/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/free/Assets' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/free/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/free/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/free/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/friction/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/friction/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/friction/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/gravity/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/gravity/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/gravity/stack' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/gravity/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/gyro/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/isStatic/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/isStatic/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/isStatic/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/lib/decomp' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/lib/interrupt' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/lib/matter-tools.demo' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/lib/matter-tools.gui' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/lib/matter-tools.inspector' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/manipulation/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/matter' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/mixed/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/newtonsCradle/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/newtonsCradle/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/newtonsCradle/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/plugins/attractorsPlugin' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/plugins/gravityPlugin' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/plugins/wrapPlugin' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/pyramid/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/pyramid/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/pyramid/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/raycasting/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/rectangle/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/rectangle/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/rectangle/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/render' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/render/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/render/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/render/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/renderConfigs' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/restitution/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/restitution/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/restitution/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/rounded/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/rounded/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/rounded/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/sensors/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/sleeping/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/slingshot/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/slingshot/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/slingshot/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/softBody/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/softBody/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/softBody/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/sprites/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/stack' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/stack/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/stack/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/stack/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/staticFriction/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/staticFriction/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/staticFriction/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/stress/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/stress2/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/svg/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/terrain/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/timescale/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/timescaleSimple/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/timescaleSimple/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/timescaleSimple/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/views/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/wreckingBall/main' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/wreckingBall/setting' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/matterjs/wreckingBall/stage' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/game' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/lib/interrupt' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/lib/polyfill' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/agent' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/block-manager' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/block-names' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/core' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/event-emitter' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/player' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/synonyms' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/utils' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/minecraft/utils/create-snippet' {
  declare module.exports: any;
}

declare module 'feeles-ide/samples/mc/raw-loader' {
  declare module.exports: any;
}

declare module 'feeles-ide/server' {
  declare module.exports: any;
}

declare module 'feeles-ide/umd/index' {
  declare module.exports: any;
}

declare module 'feeles-ide/version' {
  declare module.exports: any;
}

declare module 'feeles-ide/versioning-webpack-plugin' {
  declare module.exports: any;
}

declare module 'feeles-ide/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feeles-ide/feeles-webpack-plugin.js' {
  declare module.exports: $Exports<'feeles-ide/feeles-webpack-plugin'>;
}
declare module 'feeles-ide/lib/Cards/CardContainer.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/CardContainer'>;
}
declare module 'feeles-ide/lib/Cards/CardWindow.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/CardWindow'>;
}
declare module 'feeles-ide/lib/Cards/CreditsCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/CreditsCard/index'>;
}
declare module 'feeles-ide/lib/Cards/CustomizeCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/CustomizeCard/index'>;
}
declare module 'feeles-ide/lib/Cards/defaultState.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/defaultState'>;
}
declare module 'feeles-ide/lib/Cards/EditFile.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditFile'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/AssetButton.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/AssetButton'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/AssetPane.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/AssetPane'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/codemirror-hint-extension.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/codemirror-hint-extension'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/CreditBar.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/CreditBar'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/Editor.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/Editor'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/ErrorPane.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/ErrorPane'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/index'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/PlayMenu.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/PlayMenu'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/Preview.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/Preview'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/SourceEditor.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/SourceEditor'>;
}
declare module 'feeles-ide/lib/Cards/EditorCard/zenkakuToHankaku.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EditorCard/zenkakuToHankaku'>;
}
declare module 'feeles-ide/lib/Cards/EnvCard/EnvItem.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EnvCard/EnvItem'>;
}
declare module 'feeles-ide/lib/Cards/EnvCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/EnvCard/index'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/DesktopFile.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/DesktopFile'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/DirCard.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/DirCard'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/FileCard.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/FileCard'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/Filename.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/Filename'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/getHierarchy.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/getHierarchy'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/index'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/Root.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/Root'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/search.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/search'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/SearchBar.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/SearchBar'>;
}
declare module 'feeles-ide/lib/Cards/HierarchyCard/TrashBox.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/HierarchyCard/TrashBox'>;
}
declare module 'feeles-ide/lib/Cards/MediaCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MediaCard/index'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/ErrorMessage.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/ErrorMessage'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/index'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/Monitor.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/Monitor'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/registerHTML.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/registerHTML'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/ResolveProgress.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/ResolveProgress'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/Screen.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/Screen'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/setSrcDoc.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/setSrcDoc'>;
}
declare module 'feeles-ide/lib/Cards/MonitorCard/SvgButton.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/MonitorCard/SvgButton'>;
}
declare module 'feeles-ide/lib/Cards/PaletteCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/PaletteCard/index'>;
}
declare module 'feeles-ide/lib/Cards/PaletteCard/LayeredStyle.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/PaletteCard/LayeredStyle'>;
}
declare module 'feeles-ide/lib/Cards/ReadmeCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ReadmeCard/index'>;
}
declare module 'feeles-ide/lib/Cards/ReadmeCard/Readme.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ReadmeCard/Readme'>;
}
declare module 'feeles-ide/lib/Cards/ScreenShotCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ScreenShotCard/index'>;
}
declare module 'feeles-ide/lib/Cards/ShotCard/codemirror-hint-extension.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ShotCard/codemirror-hint-extension'>;
}
declare module 'feeles-ide/lib/Cards/ShotCard/Editor.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ShotCard/Editor'>;
}
declare module 'feeles-ide/lib/Cards/ShotCard/excessiveCare.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ShotCard/excessiveCare'>;
}
declare module 'feeles-ide/lib/Cards/ShotCard/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ShotCard/index'>;
}
declare module 'feeles-ide/lib/Cards/ShotCard/ShotPane.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Cards/ShotCard/ShotPane'>;
}
declare module 'feeles-ide/lib/ChromeTab/ChromeTab.js' {
  declare module.exports: $Exports<'feeles-ide/lib/ChromeTab/ChromeTab'>;
}
declare module 'feeles-ide/lib/ChromeTab/ChromeTabContent.js' {
  declare module.exports: $Exports<'feeles-ide/lib/ChromeTab/ChromeTabContent'>;
}
declare module 'feeles-ide/lib/ChromeTab/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/ChromeTab/index'>;
}
declare module 'feeles-ide/lib/ChromeTab/Tab.js' {
  declare module.exports: $Exports<'feeles-ide/lib/ChromeTab/Tab'>;
}
declare module 'feeles-ide/lib/database/FileView.js' {
  declare module.exports: $Exports<'feeles-ide/lib/database/FileView'>;
}
declare module 'feeles-ide/lib/database/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/database/index'>;
}
declare module 'feeles-ide/lib/database/personalDB.js' {
  declare module.exports: $Exports<'feeles-ide/lib/database/personalDB'>;
}
declare module 'feeles-ide/lib/File/_File.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/_File'>;
}
declare module 'feeles-ide/lib/File/babelFile.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/babelFile'>;
}
declare module 'feeles-ide/lib/File/BinaryFile.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/BinaryFile'>;
}
declare module 'feeles-ide/lib/File/composeEnv.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/composeEnv'>;
}
declare module 'feeles-ide/lib/File/configs.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/configs'>;
}
declare module 'feeles-ide/lib/File/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/index'>;
}
declare module 'feeles-ide/lib/File/JSON6.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/JSON6'>;
}
declare module 'feeles-ide/lib/File/makeFromElement.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/makeFromElement'>;
}
declare module 'feeles-ide/lib/File/makeFromFile.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/makeFromFile'>;
}
declare module 'feeles-ide/lib/File/sanitizeHTML.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/sanitizeHTML'>;
}
declare module 'feeles-ide/lib/File/separate.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/separate'>;
}
declare module 'feeles-ide/lib/File/Snippet.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/Snippet'>;
}
declare module 'feeles-ide/lib/File/SourceFile.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/SourceFile'>;
}
declare module 'feeles-ide/lib/File/validateType.js' {
  declare module.exports: $Exports<'feeles-ide/lib/File/validateType'>;
}
declare module 'feeles-ide/lib/FileDialog/AddDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/AddDialog'>;
}
declare module 'feeles-ide/lib/FileDialog/Buttons.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/Buttons'>;
}
declare module 'feeles-ide/lib/FileDialog/DeleteDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/DeleteDialog'>;
}
declare module 'feeles-ide/lib/FileDialog/FileDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/FileDialog'>;
}
declare module 'feeles-ide/lib/FileDialog/FilenameInput.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/FilenameInput'>;
}
declare module 'feeles-ide/lib/FileDialog/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/index'>;
}
declare module 'feeles-ide/lib/FileDialog/PreferenceDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/PreferenceDialog'>;
}
declare module 'feeles-ide/lib/FileDialog/SaveDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/SaveDialog'>;
}
declare module 'feeles-ide/lib/FileDialog/SignDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/FileDialog/SignDialog'>;
}
declare module 'feeles-ide/lib/js/codemirrorStyle.js' {
  declare module.exports: $Exports<'feeles-ide/lib/js/codemirrorStyle'>;
}
declare module 'feeles-ide/lib/js/getCustomTheme.js' {
  declare module.exports: $Exports<'feeles-ide/lib/js/getCustomTheme'>;
}
declare module 'feeles-ide/lib/js/isServiceWorkerEnabled.js' {
  declare module.exports: $Exports<'feeles-ide/lib/js/isServiceWorkerEnabled'>;
}
declare module 'feeles-ide/lib/jsx/EditableLabel.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/EditableLabel'>;
}
declare module 'feeles-ide/lib/jsx/Footer.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/Footer'>;
}
declare module 'feeles-ide/lib/jsx/init.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/init'>;
}
declare module 'feeles-ide/lib/jsx/LaunchDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/LaunchDialog'>;
}
declare module 'feeles-ide/lib/jsx/Main.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/Main'>;
}
declare module 'feeles-ide/lib/jsx/MDReactComponent.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/MDReactComponent'>;
}
declare module 'feeles-ide/lib/jsx/ReactPopout.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/ReactPopout'>;
}
declare module 'feeles-ide/lib/jsx/RootComponent.js' {
  declare module.exports: $Exports<'feeles-ide/lib/jsx/RootComponent'>;
}
declare module 'feeles-ide/lib/lib/connector.js' {
  declare module.exports: $Exports<'feeles-ide/lib/lib/connector'>;
}
declare module 'feeles-ide/lib/lib/escape-loader.js' {
  declare module.exports: $Exports<'feeles-ide/lib/lib/escape-loader'>;
}
declare module 'feeles-ide/lib/lib/require.js' {
  declare module.exports: $Exports<'feeles-ide/lib/lib/require'>;
}
declare module 'feeles-ide/lib/lib/screen.js' {
  declare module.exports: $Exports<'feeles-ide/lib/lib/screen'>;
}
declare module 'feeles-ide/lib/localization/en.js' {
  declare module.exports: $Exports<'feeles-ide/lib/localization/en'>;
}
declare module 'feeles-ide/lib/localization/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/localization/index'>;
}
declare module 'feeles-ide/lib/localization/ja.js' {
  declare module.exports: $Exports<'feeles-ide/lib/localization/ja'>;
}
declare module 'feeles-ide/lib/main.js' {
  declare module.exports: $Exports<'feeles-ide/lib/main'>;
}
declare module 'feeles-ide/lib/Menu/AboutDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Menu/AboutDialog'>;
}
declare module 'feeles-ide/lib/Menu/CloneDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Menu/CloneDialog'>;
}
declare module 'feeles-ide/lib/Menu/index.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Menu/index'>;
}
declare module 'feeles-ide/lib/Menu/Menu.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Menu/Menu'>;
}
declare module 'feeles-ide/lib/Menu/MetaDialog.js' {
  declare module.exports: $Exports<'feeles-ide/lib/Menu/MetaDialog'>;
}
declare module 'feeles-ide/lib/organization.js' {
  declare module.exports: $Exports<'feeles-ide/lib/organization'>;
}
declare module 'feeles-ide/lib/utils/CodeMirrorComponent.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/CodeMirrorComponent'>;
}
declare module 'feeles-ide/lib/utils/debugWindow.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/debugWindow'>;
}
declare module 'feeles-ide/lib/utils/dragTypes.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/dragTypes'>;
}
declare module 'feeles-ide/lib/utils/FacebookIcon.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/FacebookIcon'>;
}
declare module 'feeles-ide/lib/utils/GoogleIcon.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/GoogleIcon'>;
}
declare module 'feeles-ide/lib/utils/MonitorTypes.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/MonitorTypes'>;
}
declare module 'feeles-ide/lib/utils/open.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/open'>;
}
declare module 'feeles-ide/lib/utils/resolveOrigin.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/resolveOrigin'>;
}
declare module 'feeles-ide/lib/utils/Rollbar.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/Rollbar'>;
}
declare module 'feeles-ide/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/shallowEqual'>;
}
declare module 'feeles-ide/lib/utils/TwitterIcon.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/TwitterIcon'>;
}
declare module 'feeles-ide/lib/utils/uniqueBy.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/uniqueBy'>;
}
declare module 'feeles-ide/lib/utils/uniqueId.js' {
  declare module.exports: $Exports<'feeles-ide/lib/utils/uniqueId'>;
}
declare module 'feeles-ide/lib/workers/babel.worker.js' {
  declare module.exports: $Exports<'feeles-ide/lib/workers/babel.worker'>;
}
declare module 'feeles-ide/samples/ask/ask.js' {
  declare module.exports: $Exports<'feeles-ide/samples/ask/ask'>;
}
declare module 'feeles-ide/samples/ask/icon.js' {
  declare module.exports: $Exports<'feeles-ide/samples/ask/icon'>;
}
declare module 'feeles-ide/samples/ask/index.js' {
  declare module.exports: $Exports<'feeles-ide/samples/ask/index'>;
}
declare module 'feeles-ide/samples/ask/internet.js' {
  declare module.exports: $Exports<'feeles-ide/samples/ask/internet'>;
}
declare module 'feeles-ide/samples/ask/lib/interrupt.js' {
  declare module.exports: $Exports<'feeles-ide/samples/ask/lib/interrupt'>;
}
declare module 'feeles-ide/samples/ask/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/ask/main'>;
}
declare module 'feeles-ide/samples/hello-world/feeles/eval.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/feeles/eval'>;
}
declare module 'feeles-ide/samples/hello-world/i18n/en_US/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/i18n/en_US/main'>;
}
declare module 'feeles-ide/samples/hello-world/i18n/en_US/preload.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/i18n/en_US/preload'>;
}
declare module 'feeles-ide/samples/hello-world/i18n/ja_JP/code.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/i18n/ja_JP/code'>;
}
declare module 'feeles-ide/samples/hello-world/i18n/ja_JP/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/i18n/ja_JP/main'>;
}
declare module 'feeles-ide/samples/hello-world/i18n/ja_JP/preload.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/i18n/ja_JP/preload'>;
}
declare module 'feeles-ide/samples/hello-world/lib/interrupt.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/lib/interrupt'>;
}
declare module 'feeles-ide/samples/hello-world/sub/message.js' {
  declare module.exports: $Exports<'feeles-ide/samples/hello-world/sub/message'>;
}
declare module 'feeles-ide/samples/matterjs/airFriction/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/airFriction/main'>;
}
declare module 'feeles-ide/samples/matterjs/airFriction/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/airFriction/setting'>;
}
declare module 'feeles-ide/samples/matterjs/airFriction/settings.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/airFriction/settings'>;
}
declare module 'feeles-ide/samples/matterjs/airFriction/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/airFriction/stage'>;
}
declare module 'feeles-ide/samples/matterjs/angle/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/angle/main'>;
}
declare module 'feeles-ide/samples/matterjs/angle/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/angle/setting'>;
}
declare module 'feeles-ide/samples/matterjs/angle/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/angle/stage'>;
}
declare module 'feeles-ide/samples/matterjs/attractors/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/attractors/main'>;
}
declare module 'feeles-ide/samples/matterjs/avalanche/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/avalanche/main'>;
}
declare module 'feeles-ide/samples/matterjs/ballPool/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/ballPool/main'>;
}
declare module 'feeles-ide/samples/matterjs/bridge/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/bridge/main'>;
}
declare module 'feeles-ide/samples/matterjs/bridge/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/bridge/setting'>;
}
declare module 'feeles-ide/samples/matterjs/bridge/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/bridge/stage'>;
}
declare module 'feeles-ide/samples/matterjs/broadphase/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/broadphase/main'>;
}
declare module 'feeles-ide/samples/matterjs/car/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/car/main'>;
}
declare module 'feeles-ide/samples/matterjs/car/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/car/setting'>;
}
declare module 'feeles-ide/samples/matterjs/car/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/car/stage'>;
}
declare module 'feeles-ide/samples/matterjs/catapult/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/catapult/main'>;
}
declare module 'feeles-ide/samples/matterjs/catapult/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/catapult/setting'>;
}
declare module 'feeles-ide/samples/matterjs/catapult/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/catapult/stage'>;
}
declare module 'feeles-ide/samples/matterjs/chains/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/chains/main'>;
}
declare module 'feeles-ide/samples/matterjs/chains/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/chains/setting'>;
}
declare module 'feeles-ide/samples/matterjs/chamfer/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/chamfer/main'>;
}
declare module 'feeles-ide/samples/matterjs/chamfer/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/chamfer/setting'>;
}
declare module 'feeles-ide/samples/matterjs/chamfer/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/chamfer/stage'>;
}
declare module 'feeles-ide/samples/matterjs/circleStack/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/circleStack/main'>;
}
declare module 'feeles-ide/samples/matterjs/circleStack/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/circleStack/setting'>;
}
declare module 'feeles-ide/samples/matterjs/circleStack/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/circleStack/stage'>;
}
declare module 'feeles-ide/samples/matterjs/cloth/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/cloth/main'>;
}
declare module 'feeles-ide/samples/matterjs/coins/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/coins/main'>;
}
declare module 'feeles-ide/samples/matterjs/coins/sensor.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/coins/sensor'>;
}
declare module 'feeles-ide/samples/matterjs/coins/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/coins/setting'>;
}
declare module 'feeles-ide/samples/matterjs/coins/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/coins/stage'>;
}
declare module 'feeles-ide/samples/matterjs/collisionFiltering/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/collisionFiltering/main'>;
}
declare module 'feeles-ide/samples/matterjs/compositeManipulation/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/compositeManipulation/main'>;
}
declare module 'feeles-ide/samples/matterjs/compound/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/compound/main'>;
}
declare module 'feeles-ide/samples/matterjs/compound/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/compound/setting'>;
}
declare module 'feeles-ide/samples/matterjs/compound/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/compound/stage'>;
}
declare module 'feeles-ide/samples/matterjs/compoundStack/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/compoundStack/main'>;
}
declare module 'feeles-ide/samples/matterjs/compoundStack/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/compoundStack/setting'>;
}
declare module 'feeles-ide/samples/matterjs/compoundStack/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/compoundStack/stage'>;
}
declare module 'feeles-ide/samples/matterjs/concave/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/concave/main'>;
}
declare module 'feeles-ide/samples/matterjs/constraint/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/constraint/main'>;
}
declare module 'feeles-ide/samples/matterjs/constraint/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/constraint/setting'>;
}
declare module 'feeles-ide/samples/matterjs/constraint/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/constraint/stage'>;
}
declare module 'feeles-ide/samples/matterjs/density/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/density/main'>;
}
declare module 'feeles-ide/samples/matterjs/density/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/density/setting'>;
}
declare module 'feeles-ide/samples/matterjs/density/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/density/stage'>;
}
declare module 'feeles-ide/samples/matterjs/engine.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/engine'>;
}
declare module 'feeles-ide/samples/matterjs/engineConfigs.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/engineConfigs'>;
}
declare module 'feeles-ide/samples/matterjs/events/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/events/main'>;
}
declare module 'feeles-ide/samples/matterjs/free/Assets.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/free/Assets'>;
}
declare module 'feeles-ide/samples/matterjs/free/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/free/main'>;
}
declare module 'feeles-ide/samples/matterjs/free/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/free/setting'>;
}
declare module 'feeles-ide/samples/matterjs/free/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/free/stage'>;
}
declare module 'feeles-ide/samples/matterjs/friction/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/friction/main'>;
}
declare module 'feeles-ide/samples/matterjs/friction/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/friction/setting'>;
}
declare module 'feeles-ide/samples/matterjs/friction/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/friction/stage'>;
}
declare module 'feeles-ide/samples/matterjs/gravity/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/gravity/main'>;
}
declare module 'feeles-ide/samples/matterjs/gravity/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/gravity/setting'>;
}
declare module 'feeles-ide/samples/matterjs/gravity/stack.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/gravity/stack'>;
}
declare module 'feeles-ide/samples/matterjs/gravity/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/gravity/stage'>;
}
declare module 'feeles-ide/samples/matterjs/gyro/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/gyro/main'>;
}
declare module 'feeles-ide/samples/matterjs/isStatic/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/isStatic/main'>;
}
declare module 'feeles-ide/samples/matterjs/isStatic/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/isStatic/setting'>;
}
declare module 'feeles-ide/samples/matterjs/isStatic/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/isStatic/stage'>;
}
declare module 'feeles-ide/samples/matterjs/lib/decomp.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/lib/decomp'>;
}
declare module 'feeles-ide/samples/matterjs/lib/interrupt.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/lib/interrupt'>;
}
declare module 'feeles-ide/samples/matterjs/lib/matter-tools.demo.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/lib/matter-tools.demo'>;
}
declare module 'feeles-ide/samples/matterjs/lib/matter-tools.gui.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/lib/matter-tools.gui'>;
}
declare module 'feeles-ide/samples/matterjs/lib/matter-tools.inspector.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/lib/matter-tools.inspector'>;
}
declare module 'feeles-ide/samples/matterjs/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/main'>;
}
declare module 'feeles-ide/samples/matterjs/manipulation/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/manipulation/main'>;
}
declare module 'feeles-ide/samples/matterjs/matter.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/matter'>;
}
declare module 'feeles-ide/samples/matterjs/mixed/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/mixed/main'>;
}
declare module 'feeles-ide/samples/matterjs/newtonsCradle/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/newtonsCradle/main'>;
}
declare module 'feeles-ide/samples/matterjs/newtonsCradle/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/newtonsCradle/setting'>;
}
declare module 'feeles-ide/samples/matterjs/newtonsCradle/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/newtonsCradle/stage'>;
}
declare module 'feeles-ide/samples/matterjs/plugins/attractorsPlugin.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/plugins/attractorsPlugin'>;
}
declare module 'feeles-ide/samples/matterjs/plugins/gravityPlugin.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/plugins/gravityPlugin'>;
}
declare module 'feeles-ide/samples/matterjs/plugins/wrapPlugin.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/plugins/wrapPlugin'>;
}
declare module 'feeles-ide/samples/matterjs/pyramid/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/pyramid/main'>;
}
declare module 'feeles-ide/samples/matterjs/pyramid/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/pyramid/setting'>;
}
declare module 'feeles-ide/samples/matterjs/pyramid/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/pyramid/stage'>;
}
declare module 'feeles-ide/samples/matterjs/raycasting/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/raycasting/main'>;
}
declare module 'feeles-ide/samples/matterjs/rectangle/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/rectangle/main'>;
}
declare module 'feeles-ide/samples/matterjs/rectangle/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/rectangle/setting'>;
}
declare module 'feeles-ide/samples/matterjs/rectangle/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/rectangle/stage'>;
}
declare module 'feeles-ide/samples/matterjs/render.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/render'>;
}
declare module 'feeles-ide/samples/matterjs/render/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/render/main'>;
}
declare module 'feeles-ide/samples/matterjs/render/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/render/setting'>;
}
declare module 'feeles-ide/samples/matterjs/render/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/render/stage'>;
}
declare module 'feeles-ide/samples/matterjs/renderConfigs.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/renderConfigs'>;
}
declare module 'feeles-ide/samples/matterjs/restitution/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/restitution/main'>;
}
declare module 'feeles-ide/samples/matterjs/restitution/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/restitution/setting'>;
}
declare module 'feeles-ide/samples/matterjs/restitution/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/restitution/stage'>;
}
declare module 'feeles-ide/samples/matterjs/rounded/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/rounded/main'>;
}
declare module 'feeles-ide/samples/matterjs/rounded/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/rounded/setting'>;
}
declare module 'feeles-ide/samples/matterjs/rounded/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/rounded/stage'>;
}
declare module 'feeles-ide/samples/matterjs/sensors/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/sensors/main'>;
}
declare module 'feeles-ide/samples/matterjs/sleeping/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/sleeping/main'>;
}
declare module 'feeles-ide/samples/matterjs/slingshot/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/slingshot/main'>;
}
declare module 'feeles-ide/samples/matterjs/slingshot/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/slingshot/setting'>;
}
declare module 'feeles-ide/samples/matterjs/slingshot/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/slingshot/stage'>;
}
declare module 'feeles-ide/samples/matterjs/softBody/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/softBody/main'>;
}
declare module 'feeles-ide/samples/matterjs/softBody/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/softBody/setting'>;
}
declare module 'feeles-ide/samples/matterjs/softBody/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/softBody/stage'>;
}
declare module 'feeles-ide/samples/matterjs/sprites/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/sprites/main'>;
}
declare module 'feeles-ide/samples/matterjs/stack.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/stack'>;
}
declare module 'feeles-ide/samples/matterjs/stack/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/stack/main'>;
}
declare module 'feeles-ide/samples/matterjs/stack/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/stack/setting'>;
}
declare module 'feeles-ide/samples/matterjs/stack/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/stack/stage'>;
}
declare module 'feeles-ide/samples/matterjs/staticFriction/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/staticFriction/main'>;
}
declare module 'feeles-ide/samples/matterjs/staticFriction/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/staticFriction/setting'>;
}
declare module 'feeles-ide/samples/matterjs/staticFriction/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/staticFriction/stage'>;
}
declare module 'feeles-ide/samples/matterjs/stress/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/stress/main'>;
}
declare module 'feeles-ide/samples/matterjs/stress2/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/stress2/main'>;
}
declare module 'feeles-ide/samples/matterjs/svg/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/svg/main'>;
}
declare module 'feeles-ide/samples/matterjs/terrain/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/terrain/main'>;
}
declare module 'feeles-ide/samples/matterjs/timescale/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/timescale/main'>;
}
declare module 'feeles-ide/samples/matterjs/timescaleSimple/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/timescaleSimple/main'>;
}
declare module 'feeles-ide/samples/matterjs/timescaleSimple/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/timescaleSimple/setting'>;
}
declare module 'feeles-ide/samples/matterjs/timescaleSimple/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/timescaleSimple/stage'>;
}
declare module 'feeles-ide/samples/matterjs/views/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/views/main'>;
}
declare module 'feeles-ide/samples/matterjs/wreckingBall/main.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/wreckingBall/main'>;
}
declare module 'feeles-ide/samples/matterjs/wreckingBall/setting.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/wreckingBall/setting'>;
}
declare module 'feeles-ide/samples/matterjs/wreckingBall/stage.js' {
  declare module.exports: $Exports<'feeles-ide/samples/matterjs/wreckingBall/stage'>;
}
declare module 'feeles-ide/samples/mc/game.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/game'>;
}
declare module 'feeles-ide/samples/mc/lib/interrupt.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/lib/interrupt'>;
}
declare module 'feeles-ide/samples/mc/lib/polyfill.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/lib/polyfill'>;
}
declare module 'feeles-ide/samples/mc/minecraft/agent.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/agent'>;
}
declare module 'feeles-ide/samples/mc/minecraft/block-manager.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/block-manager'>;
}
declare module 'feeles-ide/samples/mc/minecraft/block-names.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/block-names'>;
}
declare module 'feeles-ide/samples/mc/minecraft/core.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/core'>;
}
declare module 'feeles-ide/samples/mc/minecraft/event-emitter.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/event-emitter'>;
}
declare module 'feeles-ide/samples/mc/minecraft/player.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/player'>;
}
declare module 'feeles-ide/samples/mc/minecraft/synonyms.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/synonyms'>;
}
declare module 'feeles-ide/samples/mc/minecraft/utils.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/utils'>;
}
declare module 'feeles-ide/samples/mc/minecraft/utils/create-snippet.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/minecraft/utils/create-snippet'>;
}
declare module 'feeles-ide/samples/mc/raw-loader.js' {
  declare module.exports: $Exports<'feeles-ide/samples/mc/raw-loader'>;
}
declare module 'feeles-ide/server.js' {
  declare module.exports: $Exports<'feeles-ide/server'>;
}
declare module 'feeles-ide/umd/index.js' {
  declare module.exports: $Exports<'feeles-ide/umd/index'>;
}
declare module 'feeles-ide/version.js' {
  declare module.exports: $Exports<'feeles-ide/version'>;
}
declare module 'feeles-ide/versioning-webpack-plugin.js' {
  declare module.exports: $Exports<'feeles-ide/versioning-webpack-plugin'>;
}
declare module 'feeles-ide/webpack.config.js' {
  declare module.exports: $Exports<'feeles-ide/webpack.config'>;
}
