// flow-typed signature: 56ea4e9478c3f5b0e551ec3630d4db0e
// flow-typed version: <<STUB>>/firestore-seed_v0.0.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firestore-seed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firestore-seed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firestore-seed/examples/chat/index' {
  declare module.exports: any;
}

declare module 'firestore-seed/examples/geopoint/index' {
  declare module.exports: any;
}

declare module 'firestore-seed/examples/simple/index' {
  declare module.exports: any;
}

declare module 'firestore-seed/examples/upload/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firestore-seed/examples/chat/index.js' {
  declare module.exports: $Exports<'firestore-seed/examples/chat/index'>;
}
declare module 'firestore-seed/examples/geopoint/index.js' {
  declare module.exports: $Exports<'firestore-seed/examples/geopoint/index'>;
}
declare module 'firestore-seed/examples/simple/index.js' {
  declare module.exports: $Exports<'firestore-seed/examples/simple/index'>;
}
declare module 'firestore-seed/examples/upload/index.js' {
  declare module.exports: $Exports<'firestore-seed/examples/upload/index'>;
}
declare module 'firestore-seed/index' {
  declare module.exports: $Exports<'firestore-seed'>;
}
declare module 'firestore-seed/index.js' {
  declare module.exports: $Exports<'firestore-seed'>;
}
