// flow-typed signature: 1a9a19599d35c8b532f4dbc35aba32b4
// flow-typed version: <<STUB>>/generate-robotstxt_v^5.0.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generate-robotstxt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generate-robotstxt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generate-robotstxt/dist/cli' {
  declare module.exports: any;
}

declare module 'generate-robotstxt/dist/index' {
  declare module.exports: any;
}

declare module 'generate-robotstxt/dist/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generate-robotstxt/dist/cli.js' {
  declare module.exports: $Exports<'generate-robotstxt/dist/cli'>;
}
declare module 'generate-robotstxt/dist/index.js' {
  declare module.exports: $Exports<'generate-robotstxt/dist/index'>;
}
declare module 'generate-robotstxt/dist/standalone.js' {
  declare module.exports: $Exports<'generate-robotstxt/dist/standalone'>;
}
