// flow-typed signature: d5ae7d9511ffb1dd709a3ea32b0b2810
// flow-typed version: <<STUB>>/react-map-editor_v^0.1.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-map-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-map-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-map-editor/ava.config' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/components/CanvasView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/components/LayerView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/components/MenuBar' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/components/PaletteView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/components/Root' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/containers/CanvasView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/containers/LayerView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/containers/MenuBar' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/containers/PaletteView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/containers/Root' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/example' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/icons/Edit' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/icons/Eraser' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/index' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/asset' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/canvas' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/canvas.spec' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/core' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/createStore' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/index' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/input' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/mode' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/palette' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/scene' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/redux/typescript-fsa-redux-observable' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/components/CanvasView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/components/LayerView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/components/MenuBar' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/components/PaletteView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/containers/CanvasView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/containers/LayerView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/containers/MenuBar' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/containers/PaletteView' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/example' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/icons/Edit' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/icons/Eraser' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/index' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/redux/canvas' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/redux/createStore' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/redux/index' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/redux/input' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/redux/mode' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/redux/palette' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/redux/typescript-fsa-redux-observable' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/src/utils/pen' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/tilesets/pipoya' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/typings' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/utils/cursor' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/utils/pen' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/utils/selection' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/utils/selection.spec' {
  declare module.exports: any;
}

declare module 'react-map-editor/lib/webpack.config' {
  declare module.exports: any;
}

declare module 'react-map-editor/svgr-template' {
  declare module.exports: any;
}

declare module 'react-map-editor/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-map-editor/ava.config.js' {
  declare module.exports: $Exports<'react-map-editor/ava.config'>;
}
declare module 'react-map-editor/lib/components/CanvasView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/components/CanvasView'>;
}
declare module 'react-map-editor/lib/components/LayerView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/components/LayerView'>;
}
declare module 'react-map-editor/lib/components/MenuBar.js' {
  declare module.exports: $Exports<'react-map-editor/lib/components/MenuBar'>;
}
declare module 'react-map-editor/lib/components/PaletteView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/components/PaletteView'>;
}
declare module 'react-map-editor/lib/components/Root.js' {
  declare module.exports: $Exports<'react-map-editor/lib/components/Root'>;
}
declare module 'react-map-editor/lib/containers/CanvasView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/containers/CanvasView'>;
}
declare module 'react-map-editor/lib/containers/LayerView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/containers/LayerView'>;
}
declare module 'react-map-editor/lib/containers/MenuBar.js' {
  declare module.exports: $Exports<'react-map-editor/lib/containers/MenuBar'>;
}
declare module 'react-map-editor/lib/containers/PaletteView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/containers/PaletteView'>;
}
declare module 'react-map-editor/lib/containers/Root.js' {
  declare module.exports: $Exports<'react-map-editor/lib/containers/Root'>;
}
declare module 'react-map-editor/lib/example.js' {
  declare module.exports: $Exports<'react-map-editor/lib/example'>;
}
declare module 'react-map-editor/lib/icons/Edit.js' {
  declare module.exports: $Exports<'react-map-editor/lib/icons/Edit'>;
}
declare module 'react-map-editor/lib/icons/Eraser.js' {
  declare module.exports: $Exports<'react-map-editor/lib/icons/Eraser'>;
}
declare module 'react-map-editor/lib/index.js' {
  declare module.exports: $Exports<'react-map-editor/lib/index'>;
}
declare module 'react-map-editor/lib/redux/asset.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/asset'>;
}
declare module 'react-map-editor/lib/redux/canvas.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/canvas'>;
}
declare module 'react-map-editor/lib/redux/canvas.spec.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/canvas.spec'>;
}
declare module 'react-map-editor/lib/redux/core.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/core'>;
}
declare module 'react-map-editor/lib/redux/createStore.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/createStore'>;
}
declare module 'react-map-editor/lib/redux/index.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/index'>;
}
declare module 'react-map-editor/lib/redux/input.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/input'>;
}
declare module 'react-map-editor/lib/redux/mode.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/mode'>;
}
declare module 'react-map-editor/lib/redux/palette.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/palette'>;
}
declare module 'react-map-editor/lib/redux/scene.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/scene'>;
}
declare module 'react-map-editor/lib/redux/typescript-fsa-redux-observable.js' {
  declare module.exports: $Exports<'react-map-editor/lib/redux/typescript-fsa-redux-observable'>;
}
declare module 'react-map-editor/lib/src/components/CanvasView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/components/CanvasView'>;
}
declare module 'react-map-editor/lib/src/components/LayerView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/components/LayerView'>;
}
declare module 'react-map-editor/lib/src/components/MenuBar.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/components/MenuBar'>;
}
declare module 'react-map-editor/lib/src/components/PaletteView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/components/PaletteView'>;
}
declare module 'react-map-editor/lib/src/containers/CanvasView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/containers/CanvasView'>;
}
declare module 'react-map-editor/lib/src/containers/LayerView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/containers/LayerView'>;
}
declare module 'react-map-editor/lib/src/containers/MenuBar.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/containers/MenuBar'>;
}
declare module 'react-map-editor/lib/src/containers/PaletteView.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/containers/PaletteView'>;
}
declare module 'react-map-editor/lib/src/example.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/example'>;
}
declare module 'react-map-editor/lib/src/icons/Edit.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/icons/Edit'>;
}
declare module 'react-map-editor/lib/src/icons/Eraser.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/icons/Eraser'>;
}
declare module 'react-map-editor/lib/src/index.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/index'>;
}
declare module 'react-map-editor/lib/src/redux/canvas.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/redux/canvas'>;
}
declare module 'react-map-editor/lib/src/redux/createStore.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/redux/createStore'>;
}
declare module 'react-map-editor/lib/src/redux/index.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/redux/index'>;
}
declare module 'react-map-editor/lib/src/redux/input.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/redux/input'>;
}
declare module 'react-map-editor/lib/src/redux/mode.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/redux/mode'>;
}
declare module 'react-map-editor/lib/src/redux/palette.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/redux/palette'>;
}
declare module 'react-map-editor/lib/src/redux/typescript-fsa-redux-observable.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/redux/typescript-fsa-redux-observable'>;
}
declare module 'react-map-editor/lib/src/utils/pen.js' {
  declare module.exports: $Exports<'react-map-editor/lib/src/utils/pen'>;
}
declare module 'react-map-editor/lib/tilesets/pipoya.js' {
  declare module.exports: $Exports<'react-map-editor/lib/tilesets/pipoya'>;
}
declare module 'react-map-editor/lib/typings.js' {
  declare module.exports: $Exports<'react-map-editor/lib/typings'>;
}
declare module 'react-map-editor/lib/utils/cursor.js' {
  declare module.exports: $Exports<'react-map-editor/lib/utils/cursor'>;
}
declare module 'react-map-editor/lib/utils/pen.js' {
  declare module.exports: $Exports<'react-map-editor/lib/utils/pen'>;
}
declare module 'react-map-editor/lib/utils/selection.js' {
  declare module.exports: $Exports<'react-map-editor/lib/utils/selection'>;
}
declare module 'react-map-editor/lib/utils/selection.spec.js' {
  declare module.exports: $Exports<'react-map-editor/lib/utils/selection.spec'>;
}
declare module 'react-map-editor/lib/webpack.config.js' {
  declare module.exports: $Exports<'react-map-editor/lib/webpack.config'>;
}
declare module 'react-map-editor/svgr-template.js' {
  declare module.exports: $Exports<'react-map-editor/svgr-template'>;
}
declare module 'react-map-editor/webpack.config.js' {
  declare module.exports: $Exports<'react-map-editor/webpack.config'>;
}
